language: python
python:
  - 2.6
  - 2.7
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - coverage run --source=acontrol --omit=acontrol/test/*.py $(which trial) acontrol
  - coverage run --source=aclient --omit=aclient/test/*.py $(which trial) aclient
after_success:
  coveralls
notifications:
  hipchat:
    rooms:
      secure: cTWrBxq0uqbDIpsxZs61EyHY7UfSez+imgnrjL0rwCK9Lu8xoyCjemNdyEzLFHdttte7Z0yVxz9w5NKL4G3yX9JCN7QxUjCBhtWqK1RCQ3AWBsshmd1Mh5YH+eiTBHKD9jRX8SVyIAQfppFPLedL2pvKE9NfRILbmBt7Lkyaa0c=
